### ISSUE TITLE
Failed setup, will retry: Power offs not polled: list index out of range

### ISSUE THREAD

**Issue by RuslanDidyk** [tsdaemon/ha-lviv-poweroff#1]
After using a guide for the installation and trying to add a new device of type 'Lviv Power Offline', an error appears on added device: **Failed setup, will retry: Power offs not polled: list index out of range**

Selected group: 1.1
Attaching logs:

```
2024-07-23 17:20:54.712 ERROR (MainThread) [custom_components.lviv_poweroff.coordinator] Cannot obtain power offs periods for group 1.1
Traceback (most recent call last):
File "/config/custom_components/lviv_poweroff/coordinator.py", line 43, in _async_update_data
await self._fetch_periods()
File "/config/custom_components/lviv_poweroff/coordinator.py", line 51, in _fetch_periods
self.periods = await self.api.get_power_off_periods()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/lviv_poweroff/energyua_scrapper.py", line 42, in get_power_off_periods
graphiks_tomorrow = grafiks[1].find_all(
~~~~~~~^^^
IndexError: list index out of range
```

**Comment by tsdaemon** [comment]
Hi @RuslanDidyk! Thank you for reporting this.  It should be fixed in this commit; please update to the latest version.
